wgb = [{'1': {'word': 'black winged kite', 'img': 'images/black-winged-kite.png'}},
       {'2': {'word': 'coppersmith barbet', 'img': 'images/coppersmith-barbet.png'}},
       {'3': {'word': 'greater coucal', 'img': 'images/greater-coucal.png'}},
       {'4': {'word': 'malabar pied hornbill', 'img': 'images/malabar-pied-hornbill.png'}},
       {'5': {'word': 'orange minivet', 'img': 'images/orange-minivet.png'}},
       {'6': {'word': 'indian golden oriole', 'img': 'images/indian-golden-oriole.png'}},
       {'7': {'word': 'oriental magpie robin', 'img': 'images/oriental-magpie-robin.png'}},
       {'8': {'word': 'red whiskered bulbul', 'img': 'images/red-whiskered-bulbul.png'}},
       {'9': {'word': 'red vented bulbul', 'img': 'images/red-vented-bulbul.png'}},
       {'10': {'word': 'rufous treepie', 'img': 'images/rufous-treepie.png'}},
       {'11': {'word': 'crested serpent eagle', 'img': 'images/crested-serpent-eagle.png'}},
       {'12': {'word': 'pied bushchat', 'img': 'images/pied-bushchat.png'}},
       {'13': {'word': 'shikra', 'img': 'images/shikra.png'}},
       {'14': {'word': 'indian jungle crow', 'img': 'images/indian-jungle-crow.png'}},
       {'15': {'word': 'tickells blue flycatcher', 'img': 'images/tickells-blue-flycatcher.png'}},
       {'16': {'word': 'white cheeked barbet', 'img': 'images/white-cheeked-barbet.png'}},
       {'17': {'word': 'grey junglefowl', 'img': 'images/grey-junglefowl.png'}},
       {'18': {'word': 'common iora', 'img': 'images/common-iora.png'}},
       {'19': {'word': 'small minivet', 'img': 'images/small-minivet.png'}},
       {'20': {'word': 'intermediate egret', 'img': 'images/intermediate-egret.png'}},
       {'21': {'word': 'indian yellow tit', 'img': 'images/indian-yellow-tit.png'}},
       {'22': {'word': 'indian grey hornbill', 'img': 'images/indian-grey-hornbill.png'}},
       {'23': {'word': 'indian scimitar babbler', 'img': 'images/indian-scimitar-babbler.png'}},
       {'24': {'word': 'laughing dove', 'img': 'images/laughing-dove.png'}},
       {'25': {'word': 'spotted dove', 'img': 'images/spotted-dove.png'}},
       {'26': {'word': 'long tailed shrike', 'img': 'images/long-tailed-shrike.png'}},
       {'27': {'word': 'black drongo', 'img': 'images/black-drongo.png'}},
       {'28': {'word': 'white rumped munia', 'img': 'images/white-rumped-munia.png'}},
       {'29': {'word': 'indian blackbird', 'img': 'images/indian-blackbird.png'}},
       {'30': {'word': 'indian peafowl', 'img': 'images/indian-peafowl.png'}},
       {'31': {'word': 'oriental honey buzzard', 'img': 'images/oriental-honey-buzzard.png'}},
       {'32': {'word': 'brahminy kite', 'img': 'images/brahminy-kite.png'}},
       {'33': {'word': 'indian vulture', 'img': 'images/indian-vulture.png'}},
       {'34': {'word': 'malabar trogon', 'img': 'images/malabar-trogon.png'}},
       {'35': {'word': 'white rumped vulture', 'img': 'images/white-rumped-vulture.png'}},
       {'36': {'word': 'jungle nightjar', 'img': 'images/jungle-nightjar.png'}},
       {'37': {'word': 'indian eagle owl', 'img': 'images/indian-eagle-owl.png'}},
       {'38': {'word': 'brown wood owl', 'img': 'images/brown-wood-owl.png'}},
       {'39': {'word': 'white throated kingfisher', 'img': 'images/white-throated-kingfisher.png'}},
       {'40': {'word': 'common kingfisher', 'img': 'images/common-kingfisher.png'}},
       {'41': {'word': 'indian roller', 'img': 'images/indian-roller.png'}},
       {'42': {'word': 'asian green beeeater', 'img': 'images/asian-green-beeeater.png'}},
       {'43': {'word': 'common kestrel', 'img': 'images/common-kestrel.png'}},
       {'44': {'word': 'indian robin', 'img': 'images/indian-robin.png'}},
       {'45': {'word': 'red breasted flycatcher', 'img': 'images/red-breasted-flycatcher.png'}},
       {'46': {'word': 'common woodshrike', 'img': 'images/common-woodshrike.png'}},
       {'47': {'word': 'jerdons leafbird', 'img': 'images/jerdons-leafbird.png'}},
       {'48': {'word': 'barn owl', 'img': 'images/barn-owl.png'}},
       {'49': {'word': 'purple sunbird', 'img': 'images/purple-sunbird.png'}},
       {'50': {'word': 'purple rumped sunbird', 'img': 'images/purple-rumped-sunbird.png'}},
       {'51': {'word': 'crimson backed sunbird', 'img': 'images/crimson-backed-sunbird.png'}},
       {'52': {'word': 'puff throated babbler', 'img': 'images/puff-throated-babbler.png'}},
       {'53': {'word': 'jungle babbler', 'img': 'images/jungle-babbler.png'}},
       {'54': {'word': 'indian pond heron', 'img': 'images/indian-pond-heron.png'}},
       {'55': {'word': 'grey heron', 'img': 'images/grey-heron.png'}},
       {'56': {'word': 'black crowned night heron', 'img': 'images/black-crowned-night-heron.png'}},
       {'57': {'word': 'common myna', 'img': 'images/common-myna.png'}},
       {'58': {'word': 'common hawk cuckoo', 'img': 'images/common-hawk-cuckoo.png'}},
       {'59': {'word': 'great hornbill', 'img': 'images/great-hornbill.png'}},
       {'60': {'word': 'red wattled lapwing', 'img': 'images/red-wattled-lapwing.png'}},
       {'61': {'word': 'white breasted waterhen', 'img': 'images/white-breasted-waterhen.png'}},
       {'62': {'word': 'indian paradise flycatcher', 'img': 'images/indian-paradise-flycatcher.png'}},
       {'63': {'word': 'little cormorant', 'img': 'images/little-cormorant.png'}},
       {'64': {'word': 'orange headed thrush', 'img': 'images/orange-headed-thrush.png'}},
       {'65': {'word': 'malabar whistling thrush', 'img': 'images/malabar-whistling-thrush.png'}},
       {'66': {'word': 'rose ringed parakeet', 'img': 'images/rose-ringed-parakeet.png'}},
       {'67': {'word': 'plum headed parakeet', 'img': 'images/plum-headed-parakeet.png'}},
       {'68': {'word': 'clamorous reed warbler', 'img': 'images/clamorous-reed-warbler.png'}},
       {'69': {'word': 'common rosefinch', 'img': 'images/common-rosefinch.png'}},
       {'70': {'word': 'brahminy starling', 'img': 'images/brahminy-starling.png'}},
       {'71': {'word': 'yellow footed green pigeon', 'img': 'images/yellow-footed-green-pigeon.png'}},
       {'72': {'word': 'brown cheeked fulvetta', 'img': 'images/brown-cheeked-fulvetta.png'}},
       {'73': {'word': 'verditer flycatcher', 'img': 'images/verditer-flycatcher.png'}},
       {'74': {'word': 'pale billed flowerpecker', 'img': 'images/verditer-flycatcher.png'}},
       {'75': {'word': 'painted francolin', 'img': 'images/painted-francolin.png'}},
       {'76': {'word': 'grey francolin', 'img': 'images/grey-francolin.png'}},
       {'77': {'word': 'common quail', 'img': 'images/common-quail.png'}},
       {'78': {'word': 'rain quail', 'img': 'images/rain-quail.png'}},
       {'79': {'word': 'king quail', 'img': 'images/king-quail.png'}},
       {'80': {'word': 'jungle bush quail', 'img': 'images/jungle-bush-quail.png'}},
       {'81': {'word': 'rock bush quail', 'img': 'images/rock-bush-quail.png'}},
       {'82': {'word': 'painted bush quail', 'img': 'images/painted-bush-quail.png'}},
       {'83': {'word': 'red spurfowl', 'img': 'images/red-spurfowl.png'}},
       {'84': {'word': 'painted spurfowl', 'img': 'images/painted-spurfowl.png'}},
       {'85': {'word': 'lesser whistling duck', 'img': 'images/lesser-whistling-duck.png'}},
       {'86': {'word': 'greylag goose', 'img': 'images/greylag-goose.png'}},
       {'87': {'word': 'bar headed goose', 'img': 'images/bar-headed-goose.png'}},
       {'88': {'word': 'knob billed duck', 'img': 'images/knob-billed-duck.png'}},
       {'89': {'word': 'ruddy shelduck', 'img': 'images/ruddy-shelduck.png'}},
       {'90': {'word': 'cotton pygmy goose', 'img': 'images/cotton-pygmy-goose.png'}},
       {'91': {'word': 'gadwall', 'img': 'images/gadwall.png'}},
       {'92': {'word': 'eurasian wigeon', 'img': 'images/eurasian-wigeon.png'}},
       {'93': {'word': 'mallard', 'img': 'images/mallard.png'}},
       {'94': {'word': 'indian spot billed duck', 'img': 'images/indian-spot-billed-duck.png'}},
       {'95': {'word': 'northern shoveler', 'img': 'images/northern-shoveler.png'}},
       {'96': {'word': 'northern pintail', 'img': 'images/northern-pintail.png'}},
       {'97': {'word': 'garganey', 'img': 'images/garganey.png'}},
       {'98': {'word': 'common teal', 'img': 'images/common-teal.png'}},
       {'99': {'word': 'red crested pochard', 'img': 'images/red-crested-pochard.png'}},
       {'100': {'word': 'common pochard', 'img': 'images/common-pochard.png'}},
       {'101': {'word': 'ferruginous duck', 'img': 'images/ferruginous-duck.png'}},
       {'102': {'word': 'tufted duck', 'img': 'images/tufted-duck.png'}},
       {'103': {'word': 'little grebe', 'img': 'images/little-grebe.png'}},
       {'104': {'word': 'painted stork', 'img': 'images/painted-stork.png'}},
       {'105': {'word': 'asian openbill', 'img': 'images/asian-openbill.png'}},
       {'106': {'word': 'black stork', 'img': 'images/black-stork.png'}},
       {'107': {'word': 'asian woolly necked stork', 'img': 'images/asian-woolly-necked-stork.png'}},
       {'108': {'word': 'white stork', 'img': 'images/white-stork.png'}},
       {'109': {'word': 'lesser adjutant', 'img': 'images/lesser-adjutant.png'}},
       {'110': {'word': 'greater flamingo', 'img': 'images/greater-flamingo.png'}},
       {'111': {'word': 'lesser flamingo', 'img': 'images/lesser-flamingo.png'}},
       {'112': {'word': 'black headed ibis', 'img': 'images/black-headed-ibis.png'}},
       {'113': {'word': 'red naped ibis', 'img': 'images/red-naped-ibis.png'}},
       {'114': {'word': 'glossy ibis', 'img': 'images/glossy-ibis.png'}},
       {'115': {'word': 'eurasian spoonbill', 'img': 'images/eurasian-spoonbill.png'}},
       {'116': {'word': 'black bittern', 'img': 'images/black-bittern.png'}},
       {'117': {'word': 'cinnamon bittern', 'img': 'images/cinnamon-bittern.png'}},
       {'118': {'word': 'yellow bittern', 'img': 'images/yellow-bittern.png'}},
       {'119': {'word': 'great bittern', 'img': 'images/great-bittern.png'}},
       {'120': {'word': 'striated heron', 'img': 'images/striated-heron.png'}},
       {'121': {'word': 'malayan night heron', 'img': 'images/malayan-night-heron.png'}},
       {'122': {'word': 'purple heron', 'img': 'images/purple-heron.png'}},
       {'123': {'word': 'eastern cattle egret', 'img': 'images/eastern-cattle-egret.png'}},
       {'124': {'word': 'great egret', 'img': 'images/great-egret.png'}},
       {'125': {'word': 'little egret', 'img': 'images/little-egret.png'}},
       {'126': {'word': 'western reef egret', 'img': 'images/western-reef-egret.png'}},
       {'127': {'word': 'spot billed pelican', 'img': 'images/spot-billed-pelican.png'}},
       {'128': {'word': 'oriental darter', 'img': 'images/oriental-darter.png'}},
       {'129': {'word': 'indian cormorant', 'img': 'images/indian-cormorant.png'}},
       {'130': {'word': 'great cormorant', 'img': 'images/great-cormorant.png'}},
       {'131': {'word': 'red necked falcon', 'img': 'images/red-necked-falcon.png'}},
       {'132': {'word': 'laggar falcon', 'img': 'images/laggar-falcon.png'}},
       {'133': {'word': 'peregrine falcon', 'img': 'images/peregrine-falcon.png'}},
       {'134': {'word': 'lesser kestrel', 'img': 'images/lesser-kestrel.png'}},
       {'135': {'word': 'jerdons baza', 'img': 'images/jerdons-baza.png'}},
       {'136': {'word': 'black baza', 'img': 'images/black-baza.png'}},
       {'137': {'word': 'black kite', 'img': 'images/black-kite.png'}},
       {'138': {'word': 'osprey', 'img': 'images/osprey.png'}},
       {'139': {'word': 'white bellied sea eagle', 'img': 'images/white-bellied-sea-eagle.png'}},
       {'140': {'word': 'lesser fish eagle', 'img': 'images/lesser-fish-eagle.png'}},
       {'141': {'word': 'grey headed fish eagle', 'img': 'images/grey-headed-fish-eagle.png'}},
       {'142': {'word': 'black eagle', 'img': 'images/black-eagle.png'}},
       {'143': {'word': 'egyptian vulture', 'img': 'images/egyptian-vulture.png'}},
       {'144': {'word': 'short toed snake eagle', 'img': 'images/short-toed-snake-eagle.png'}},
       {'145': {'word': 'eurasian marsh harrier', 'img': 'images/eurasian-marsh-harrier.png'}},
       {'146': {'word': 'pallid harrier', 'img': 'images/pallid-harrier.png'}},
       {'147': {'word': 'montagus harrier', 'img': 'images/montagus-harrier.png'}},
       {'148': {'word': 'pied harrier', 'img': 'images/pied-harrier.png'}},
       {'149': {'word': 'crested goshawk', 'img': 'images/crested-goshawk.png'}},
       {'150': {'word': 'besra', 'img': 'images/besra.png'}},
       {'151': {'word': 'eurasian sparrowhawk', 'img': 'images/eurasian-sparrowhawk.png'}},
       {'152': {'word': 'white eyed buzzard', 'img': 'images/white-eyed-buzzard.png'}},
       {'153': {'word': 'common buzzard', 'img': 'images/common-buzzard.png'}},
       {'154': {'word': 'greater spotted eagle', 'img': 'images/greater-spotted-eagle.png'}},
       {'155': {'word': 'indian spotted eagle', 'img': 'images/indian-spotted-eagle.png'}},
       {'156': {'word': 'tawny eagle', 'img': 'images/tawny-eagle.png'}},
       {'157': {'word': 'steppe eagle', 'img': 'images/steppe-eagle.png'}},
       {'158': {'word': 'imperial eagle', 'img': 'images/imperial-eagle.png'}},
       {'159': {'word': 'bonellis eagle', 'img': 'images/bonellis-eagle.png'}},
       {'160': {'word': 'booted eagle', 'img': 'images/booted-eagle.png'}},
       {'161': {'word': 'rufous bellied eagle', 'img': 'images/rufous-bellied-eagle.png'}},
       {'162': {'word': 'crested hawk eagle', 'img': 'images/crested-hawk-eagle.png'}},
       {'163': {'word': 'legges hawk eagle', 'img': 'images/imperial-eagle.png'}},
       {'164': {'word': 'great indian bustard', 'img': 'images/great-indian-bustard.png'}},
       {'165': {'word': 'lesser florican', 'img': 'images/lesser-florican.png'}},
       {'166': {'word': 'slaty legged crake', 'img': 'images/slaty-legged-crake.png'}},
       {'167': {'word': 'slaty breasted rail', 'img': 'images/slaty-breasted-rail.png'}},
       {'168': {'word': 'baillons crake', 'img': 'images/baillons-crake.png'}},
       {'169': {'word': 'brown crake', 'img': 'images/brown-crake.png'}},
       {'170': {'word': 'spotted crake', 'img': 'images/spotted-crake.png'}},
       {'171': {'word': 'ruddy breasted crake', 'img': 'images/ruddy-breasted-crake.png'}},
       {'172': {'word': 'watercock', 'img': 'images/watercock.png'}},
       {'173': {'word': 'common coot', 'img': 'images/common-coot.png'}},
       {'174': {'word': 'common moorhen', 'img': 'images/common-moorhen.png'}},
       {'175': {'word': 'grey headed swamphen', 'img': 'images/grey-headed-swamphen.png'}},
       {'176': {'word': 'small buttonquail', 'img': 'images/small-buttonquail.png'}},
       {'177': {'word': 'yellow legged buttonquail', 'img': 'images/yellow-legged-buttonquail.png'}},
       {'178': {'word': 'barred buttonquail', 'img': 'images/barred-buttonquail.png'}},
       {'179': {'word': 'demoiselle crane', 'img': 'images/demoiselle-crane.png'}},
       {'180': {'word': 'common crane', 'img': 'images/common-crane.png'}},
       {'181': {'word': 'indian thick knee', 'img': 'images/indian-thick-knee.png'}},
       {'182': {'word': 'great thick knee', 'img': 'images/great-thick-knee.png'}},
       {'183': {'word': 'pheasant tailed jacana', 'img': 'images/pheasant-tailed-jacana.png'}},
       {'184': {'word': 'bronze winged jacana', 'img': 'images/bronze-winged-jacana.png'}},
       {'185': {'word': 'eurasian oystercatcher', 'img': 'images/eurasian-oystercatcher.png'}},
       {'186': {'word': 'pied avocet', 'img': 'images/pied-avocet.png'}},
       {'187': {'word': 'black winged stilt', 'img': 'images/black-winged-stilt.png'}},
       {'188': {'word': 'yellow wattled lapwing', 'img': 'images/yellow-wattled-lapwing.png'}},
       {'189': {'word': 'grey headed lapwing', 'img': 'images/grey-headed-lapwing.png'}},
       {'190': {'word': 'pacific golden plover', 'img': 'images/pacific-golden-plover.png'}},
       {'191': {'word': 'grey plover', 'img': 'images/grey-plover.png'}},
       {'192': {'word': 'crab plover', 'img': 'images/crab-plover.png'}},
       {'193': {'word': 'little ringed plover', 'img': 'images/little-ringed-plover.png'}},
       {'194': {'word': 'kentish plover', 'img': 'images/kentish-plover.png'}},
       {'195': {'word': 'greater sand plover', 'img': 'images/greater-sand-plover.png'}},
       {'196': {'word': 'lesser sand plover', 'img': 'images/lesser-sand-plover.png'}},
       # {'197': {'word': 'greater painted snipe', 'img': 'images/greater-painted-snipe.png'}},
       # {'198': {'word': 'eurasian woodcock', 'img': 'images/eurasian-woodcock.png'}},
       # {'199': {'word': 'ruff', 'img': 'images/ruff.png'}},
       # {'200': {'word': 'red necked phalarope', 'img': 'images/red-necked-phalarope.png'}},
       # {'201': {'word': 'jack snipe', 'img': 'images/jack-snipe.png'}},
       # {'202': {'word': 'wood snipe', 'img': 'images/wood-snipe.png'}},
       # {'203': {'word': 'pin tailed snipe', 'img': 'images/pin-tailed-snipe.png'}},
       # {'204': {'word': 'swinhoes snipe', 'img': 'images/swinhoes-snipe.png'}},
       # {'205': {'word': 'common snipe', 'img': 'images/common-snipe.png'}},
       # {'206': {'word': 'black tailed godwit', 'img': 'images/black-tailed-godwit.png'}},
       # {'207': {'word': 'bar tailed godwit', 'img': 'images/bar-tailed-godwit.png'}},
       # {'208': {'word': 'whimbrel', 'img': 'images/whimbrel.png'}},
       # {'209': {'word': 'eurasian curlew', 'img': 'images/eurasian-curlew.png'}},
       # {'210': {'word': 'spotted redshank', 'img': 'images/spotted-redshank.png'}},
       # {'211': {'word': 'common-redshank', 'img': 'images/common-redshank.png'}},
       # {'212': {'word': 'marsh sandpiper', 'img': 'images/marsh-sandpiper.png'}},
       # {'213': {'word': 'common greenshank', 'img': 'images/common-greenshank.png'}},
       # {'214': {'word': 'green sandpiper', 'img': 'images/green-sandpiper.png'}},
       # {'215': {'word': 'wood sandpiper', 'img': 'images/wood-sandpiper.png'}},
       # {'216': {'word': 'terek sandpiper', 'img': 'images/terek-sandpiper.png'}},
       # {'217': {'word': 'common sandpiper', 'img': 'images/common-sandpiper.png'}},
       # {'218': {'word': 'ruddy turnstone', 'img': 'images/ruddy-turnstone.png'}},
       # {'219': {'word': 'great knot', 'img': 'images/great-knot.png'}},
       # {'220': {'word': 'red knot', 'img': 'images/red-knot.png'}},
       # {'221': {'word': 'little stint', 'img': 'images/little-stint.png'}},
       # {'222': {'word': 'temmincks stint', 'img': 'images/temmincks-stint.png'}},
       # {'223': {'word': 'long toed stint', 'img': 'images/long-toed-stint.png'}},
       # {'224': {'word': 'curlew sandpiper', 'img': 'images/curlew-sandpiper.png'}},
       # {'225': {'word': 'sanderling', 'img': 'images/sanderling.png'}},
       # {'226': {'word': 'dunlin', 'img': 'images/dunlin.png'}},
       # {'227': {'word': 'indian courser', 'img': 'images/indian-courser.png'}},
       # {'228': {'word': 'oriental pratincole', 'img': 'images/oriental-pratincole.png'}},
       # {'229': {'word': 'small pratincole', 'img': 'images/small-pratincole.png'}},
       # {'230': {'word': 'caspian gull', 'img': 'images/caspian-gull.png'}},
       # {'231': {'word': 'heuglins gull', 'img': 'images/heuglins-gull.png'}},
       # {'232': {'word': 'steppe gull', 'img': 'images/steppe-gull.png'}},
       # {'233': {'word': 'pallas gull', 'img': 'images/pallas-gull.png'}}
]
